name: 'SemVer Tag Tracking'
description: 'Keep major and minor versioning tags update with patch.'
inputs:
  tag:
    description: Tag need to be sync.
    required: true
  token:
    description: GitHub token
    required: true
runs:
  using: node16
  main: index.js
