name: Build

on:
  workflow_dispatch:
  push:
    branches:
    - 'master'
    tags:
    - 'v*.*.*'
    paths:
    - 'action.yml'
    - 'index.ts'
    - 'pnpm-lock.yaml'
    - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install & Build
      run: |
        corepack enable
        corepack prepare pnpm@7.1.0 --activate
        pnpm i --frozen-lockfile
        pnpm build
        mv action.yml dist/action.yml

    - name: Prepare tag
      id: tag
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        TAG_NAME="${GITHUB_REF##refs/tags/}"
        echo "::set-output name=tag_name::${TAG_NAME}"
        echo "::set-output name=new_tag_name::release/${TAG_NAME}"
    - name: Distribute
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: "GitHub Actions"
        user_email: "actions@github.com"
        publish_branch: "dist"
        publish_dir: ./dist
        enable_jekyll: true # not to create .nojekyll since this is not a gh page
        commit_message: 'distribute:'
        tag_name: ${{ steps.tag.outputs.new_tag_name }} # wouldn't work if empty
        tag_message: 'distribute ${{ steps.tag.outputs.tag_name }}'
    - name: Tag Tracking
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: H4M5TER/tag-semver-tracking@dist
      with:
        tag: ${{ steps.tag.outputs.new_tag_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
